@startmindmap
* Ingénierie Biomédicale
** Biologie
*** Biochimie
*** Biophysique
*** Physiologie
** Médecine
*** Chirurgie
*** Diagnostique
*** Thérapeutique
** Ingénierie
*** Mécanique
*** Électronique
*** Informatique
*** Chimie
** Applications
*** Dispositifs médicaux
*** Biomatériaux
*** Imagerie
*** Modélisation
@endmindmap
